const fs = require('fs').promises;

async function calculador() {
  try{

  } catch (err) {

  }
}